title: YoungJin Lee
description: Personal Website

author:
  name: YoungJin Lee
  
social-network-links:
  email: "leeyou18@gmail.com"
  github: togomi
  linkedin: youngjin-lee-6b1b0430
 
share-links-active:
  email: true
  github: true
  linkedin: true
 
theme: jekyll-theme-minimal

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
